id: medcom.fhir.dk.homecareobservationstestscripts
canonical: https://medcomfhir.dk/ig/homecareobservationtestscripts
name: HomeCareObservations Testscripts
title: HomeCareObservations Testscripts
description: Testscripts for HomeCareObservations FHIR Implementation Guide
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build
publisher:
  name: MedCom
  url: medcom.dk
  email: fhir@medcom.dk

dependencies:
  medcom.fhir.dk.homecareobservation: 1.1.0-trial-use

menu:
  Home: index.html
  TouchStone Test Scripts: testscripts.html
  Test Examples - Test Protocol: testexamples.html # if relevant
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

instanceOptions:
  manualSliceOrdering: true # true | false


# TODO: Make instances of all the relevant test examples from the receive step