id: medcom.fhir.dk.homecareobservationtestscripts
canonical: http://medcomfhir.dk/ig/homecareobservationtestscripts
name: HomeCareObservations Testscripts
title: HomeCareObservations Testscripts
description: Testscripts for HomeCareObservations FHIR Implementation Guide
status: draft # draft | active | retired | unknown
version: 1.0.0-draft
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: https://medcom.dk
  email: fhir@medcom.dk

dependencies:
  medcom.fhir.dk.homecareobservation: 1.1.0-trial-use
  hl7.fhir.dk.core: 3.4.0
  medcom.fhir.dk.terminology: 2.0.0-draft
  medcom.fhir.dk.core: 2.4.0
  medcom.fhir.dk.messaging: 3.0.0
  medcom.fhir.dk.messagedefinitions: 1.0.0-trial-use

menu:
  Home: index.html
  TouchStone Test Scripts: testscripts.html
  Test Examples - Test Protocol: testexamples.html # if relevant
  Artifacts: artifacts.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true