Alias: $BundleType = http://hl7.org/fhir/bundle-type
Alias: $MessageEvents = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-eventCodes
Alias: $ProducentID = http://medcomfhir.dk/ig/terminology/CodeSystem/MedComProducentID
Alias: $DiagnosticReportCodeSystem = http://medcomfhir.dk/ig/terminology/CodeSystem/MedComDiagnosticReportCodes
Alias: $PractitionerRole = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-PractitionerRolesSKSadministrativ
Alias: $HCOActivityCodes = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-activityCodes
Alias: $ECPRCodes = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-ecpr-codes
Alias: $ObsStatusCodes = http://medcomfhir.dk/ig/terminology/ValueSet/medcom-core-observation-status
Alias: $obsInterpretation = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-core-interpretation-codes
Alias: $ObsStatusCodeSystem = http://hl7.org/fhir/observation-status
Alias: $mediastatus = http://hl7.org/fhir/event-status
Alias: $NPUObservationCodes = urn:oid:1.2.208.176.2.1 // It's also: http://medcomfhir.dk/ig/terminology/CodeSystem/npu-observation-codes
Alias: $Use = http://medcomfhir.dk/ig/terminology/CodeSystem/medcom-messaging-destinationUse
Alias: $v3-Confidentiality = http://terminology.hl7.org/CodeSystem/v3-Confidentiality
